// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaKQNrmAV-DJ1kBZGnnf1URoW1vcgamgk',
    appId: '1:249167061297:web:123f4bb62b8b81bdc85010',
    messagingSenderId: '249167061297',
    projectId: 'healthcareapp-6996a',
    authDomain: 'healthcareapp-6996a.firebaseapp.com',
    databaseURL:
        'https://healthcareapp-6996a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthcareapp-6996a.appspot.com',
    measurementId: 'G-Q7X4Y8D64B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV93cS5mBqD-klIEzXZVRpgqwfYFufGqE',
    appId: '1:249167061297:android:6970419525d2da80c85010',
    messagingSenderId: '249167061297',
    projectId: 'healthcareapp-6996a',
    databaseURL:
        'https://healthcareapp-6996a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthcareapp-6996a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjw_4KfnQIrkasZlXePAsaN_bnOsfZ6cQ',
    appId: '1:249167061297:ios:a20738dfd67c8512c85010',
    messagingSenderId: '249167061297',
    projectId: 'healthcareapp-6996a',
    databaseURL:
        'https://healthcareapp-6996a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthcareapp-6996a.appspot.com',
    androidClientId:
        '249167061297-kuaeibgbf44kve1or34ai9uvf6kd19j3.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthcareApp',
  );
}
